INSERT INTO user_profile(name, email, password)
    VALUES ('John Doe', 'john.doe@example.com', 'password');

INSERT INTO ingredient (category, name, default_measurement_unit, created_by) VALUES
('bread', 'Kaiser Bun', 'count', 1),
('dairy', 'Bleu Cheese Crumbles', 'weight', 1),
('dairy', 'Buttermilk 3.5% Milkfat', 'volume', 1),
('dairy', 'Egg', 'count', 1),
('dairy', 'Feta Cheese', 'weight', 1),
('dairy', 'Gouda Cheese', 'weight', 1),
('dairy', 'Greek Yogurt', 'weight', 1),
('dairy', 'Half & Half', 'weight', 1),
('dairy', 'Medium Cheddar', 'weight', 1),
('dairy', 'Sharp Cheddar Cheese', 'weight', 1),
('dairy', 'Sour Cream', 'weight', 1),
('dairy', 'Unsalted Butter', 'weight', 1),
('dairy', 'Whole Milk', 'volume', 1),
('grocery', 'Baking Powder', 'weight', 1),
('grocery', 'Dijon Mustard', 'volume', 1),
('grocery', 'Embasa Chipotle Pepper', 'weight', 1),
('grocery', 'Flour', 'weight', 1),
('grocery', 'Garbonzo Beans ', 'weight', 1),
('grocery', 'Horseradish', 'volume', 1),
('grocery', 'Instant Yeast', 'weight', 1),
('grocery', 'Kosher Salt', 'weight', 1),
('grocery', 'Mayonnaise', 'weight', 1),
('grocery', 'Olive OIl', 'weight', 1),
('grocery', 'Pickle Slices', 'weight', 1),
('grocery', 'Salad Soybean Oil', 'weight', 1),
('grocery', 'Spinach Wrap Tortilla 13.5 Inch', 'count', 1),
('grocery', 'Tahini', 'weight', 1),
('grocery', 'Tortilla 14 Inch', 'count', 1),
('grocery', 'Vegetable Frying Oil', 'weight', 1),
('grocery', 'White Sugar', 'weight', 1),
('grocery', 'Worcestershire Sauce', 'volume', 1),
('meat', 'Chicken Breast', 'count', 1),
('meat', 'Ground Beef', 'weight', 1),
('meat', 'Ground Turkey', 'weight', 1),
('produce', 'English Cucumber', 'weight', 1),
('produce', 'Fresh Dill', 'weight', 1),
('produce', 'Fresh Parsley', 'count', 1),
('produce', 'Fresh Thyme', 'weight', 1),
('produce', 'Garlic', 'weight', 1),
('produce', 'Green Leaf Lettuce', 'count', 1),
('produce', 'Lemon', 'weight', 1),
('produce', 'Lime', 'weight', 1),
('produce', 'Red Onion', 'weight', 1),
('produce', 'Rosemary Fresh', 'weight', 1),
('produce', 'Russet Potato', 'weight', 1),
('produce', 'Tomato', 'weight', 1),
('produce', 'Yellow Onion', 'weight', 1),
('spice', 'Celery Seed', 'weight', 1),
('spice', 'Chili Powder', 'weight', 1),
('spice', 'Chives (dried)', 'weight', 1),
('spice', 'Cumin Ground', 'weight', 1),
('spice', 'Dried rosemary (crushed)', 'weight', 1),
('spice', 'Garlic Powder', 'weight', 1),
('spice', 'Ground Black Pepper', 'weight', 1),
('spice', 'Ground Cayenne Pepper', 'weight', 1),
('spice', 'Lemon Pepper', 'weight', 1),
('spice', 'Onion Powder', 'weight', 1),
('spice', 'Oregano', 'weight', 1),
('spice', 'Parsley (dried)', 'weight', 1),
('spice', 'Smoked Paprika', 'weight', 1),
('spice', 'Thyme Leaves', 'weight', 1),
('grocery', 'Yakisoba Noodles', 'volume', 1),
('produce', 'Lemon Zest', 'volume', 1),
('produce', 'Lemon Juice', 'volume', 1),
('produce', 'Lime Juice', 'volume', 1),
('produce', 'Minced Garlic', 'volume', 1),
('recipe', 'Tres Hombres', 'volume', 1),
('recipe', 'Blackened Seasoning', 'volume', 1),
('recipe', 'Bleu Cheese Dressing', 'volume', 1),
('recipe', 'Burger Patty', 'volume', 1),
('recipe', 'Burger Sauce', 'volume', 1),
('recipe', 'Cajun Seasoning', 'volume', 1),
('recipe', 'Chipotle Mayo', 'volume', 1),
('recipe', 'Diced Tomato', 'volume', 1),
('recipe', 'Greek Seasoning', 'volume', 1),
('recipe', 'Hummus', 'volume', 1),
('recipe', 'Minced Garlic', 'volume', 1),
('recipe', 'Onion Straws', 'volume', 1),
('recipe', 'Peppercorn Ranch', 'volume', 1),
('recipe', 'Red Onion (sliced 1/8th)', 'volume', 1),
('recipe', 'Tzatziki Sauce', 'volume', 1);

INSERT INTO recipe (name, yield_quantity, yield_unit) VALUES 
('blackened seasoning', '1.93', 'oz'),
('onion straws', '27.73', 'oz'),
('tres hombres', '5.28', 'oz'),
('cajun seasoning', '3.12', 'oz'),
('greek seasoning', '2.66', 'oz'),
('chipotle mayo', '48', 'oz'),
('peppercorn ranch', '18.22', 'oz'),
('bleu cheese dressing', '22.75', 'oz'),
('hummus', '42.83', 'oz'),
('tzatziki sauce', '19.56', 'oz'),
('burger sauce', '9.57', 'oz');

INSERT INTO recipe_component (recipe_id, ingredient_id, child_recipe_id, component_type, quantity, unit) VALUES
(1,60,NULL,'ingredient',2,'tbsp'),
(1,53,NULL,'ingredient',2,'tsp'),
(1,57,NULL,'ingredient',1,'tbsp'),
(1,61,NULL,'ingredient',0.5,'tsp'),
(1,58,NULL,'ingredient',0.5,'tsp'),
(1,54,NULL,'ingredient',1,'tsp'),
(1,55,NULL,'ingredient',1,'tsp'),
(1,21,NULL,'ingredient',1,'tbsp'),
(2,47,NULL,'ingredient',1,'lb'),
(2,17,NULL,'ingredient',2,'cup'),
(2,NULL,3,'recipe',2,'tsp'),
(3,21,NULL,'ingredient',2,'tbsp'),
(3,54,NULL,'ingredient',2,'tbsp'),
(3,56,NULL,'ingredient',2,'tbsp'),
(3,51,NULL,'ingredient',2,'tbsp'),
(3,49,NULL,'ingredient',2,'tbsp'),
(3,60,NULL,'ingredient',2,'tbsp'),
(3,57,NULL,'ingredient',2,'tbsp'),
(3,53,NULL,'ingredient',2,'tbsp'),
(4,60,NULL,'ingredient',2,'tbsp'),
(4,53,NULL,'ingredient',2,'tbsp'),
(4,57,NULL,'ingredient',1.5,'tbsp'),
(4,54,NULL,'ingredient',1,'tbsp'),
(4,55,NULL,'ingredient',1,'tsp'),
(4,58,NULL,'ingredient',2,'tsp'),
(4,61,NULL,'ingredient',2,'tsp'),
(4,21,NULL,'ingredient',1.5,'tbsp'),
(5,58,NULL,'ingredient',3,'tbsp'),
(5,53,NULL,'ingredient',2,'tbsp'),
(5,57,NULL,'ingredient',1,'tbsp'),
(5,61,NULL,'ingredient',2,'tsp'),
(5,52,NULL,'ingredient',2,'tsp'),
(5,54,NULL,'ingredient',2,'tsp'),
(5,21,NULL,'ingredient',1.5,'tbsp'),
(6,22,NULL,'ingredient',2,'cup'),
(6,11,NULL,'ingredient',1,'cup'),
(6,16,NULL,'ingredient',1,'ea'),
(6,65,NULL,'ingredient',2,'tbsp'),
(6,21,NULL,'ingredient',1,'tsp'),
(7,53,NULL,'ingredient',2,'tsp'),
(7,57,NULL,'ingredient',2,'tsp'),
(7,54,NULL,'ingredient',3,'tsp'),
(7,21,NULL,'ingredient',1.5,'tsp'),
(7,59,NULL,'ingredient',2,'tsp'),
(7,50,NULL,'ingredient',2,'tsp'),
(7,48,NULL,'ingredient',0.5,'tsp'),
(7,64,NULL,'ingredient',0.5,'tsp'),
(7,22,NULL,'ingredient',1,'cup'),
(7,3,NULL,'ingredient',0.75,'cup'),
(8,22,NULL,'ingredient',0.75,'cup'),
(8,11,NULL,'ingredient',0.5,'cup'),
(8,3,NULL,'ingredient',0.25,'cup'),
(8,53,NULL,'ingredient',0.5,'tsp'),
(8,57,NULL,'ingredient',0.5,'tsp'),
(8,21,NULL,'ingredient',0.5,'tsp'),
(8,54,NULL,'ingredient',0.25,'tsp'),
(8,2,NULL,'ingredient',8,'tbsp'),
(9,18,NULL,'ingredient',1.5,'cup'),
(9,27,NULL,'ingredient',0.5,'cup'),
(9,64,NULL,'ingredient',1.5,'cup'),
(9,23,NULL,'ingredient',0.25,'cup'),
(9,66,NULL,'ingredient',4,'tsp'),
(9,21,NULL,'ingredient',1,'tbsp'),
(9,54,NULL,'ingredient',1,'tsp'),
(10,7,NULL,'ingredient',32,'tbsp'),
(10,35,NULL,'ingredient',0.5,'ea'),
(10,64,NULL,'ingredient',1,'tbsp'),
(10,23,NULL,'ingredient',1,'tbsp'),
(10,66,NULL,'ingredient',1,'tsp'),
(10,36,NULL,'ingredient',1.5,'tbsp'),
(10,21,NULL,'ingredient',0.5,'tbsp'),
(10,54,NULL,'ingredient',0.5,'tbsp'),
(10,63,NULL,'ingredient',1,'tsp'),
(11,22,NULL,'ingredient',1,'cup'),
(11,15,NULL,'ingredient',3,'tbsp'),
(11,19,NULL,'ingredient',1,'tsp');

INSERT INTO menu_item (name, target_food_cost, created_by) VALUES
('Cheeseburger',0.2,1),
('Blackened Chicken Sandwich',0.2,1),
('Black And Bleu Burger',0.2,1),
('Cajun Chicken Wrap',0.2,1),
('Greek Wrap',0.2,1);